-- =====================================================
-- CREATE PASSWORD_RESET_TOKENS TABLE
-- Stores verification codes for password reset
-- =====================================================

CREATE TABLE JAVIER.PASSWORD_RESET_TOKENS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CODIGO_CLIENTE CHAR(13) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_EXPIRACION TIMESTAMP NOT NULL,
    USADO CHAR(1) DEFAULT 'N',
    IP_SOLICITANTE VARCHAR(50),
    PRIMARY KEY (ID),
    UNIQUE (TOKEN)
);

LABEL ON TABLE JAVIER.PASSWORD_RESET_TOKENS IS 'Tokens para recuperación de contraseña';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.ID IS 'ID único autoincremental';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.CODIGO_CLIENTE IS 'Cliente solicitante';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.TOKEN IS 'Token único de recuperación';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.EMAIL IS 'Email donde se envió el token';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.FECHA_CREACION IS 'Timestamp de creación';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.FECHA_EXPIRACION IS 'Timestamp de expiración';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.USADO IS 'Token ya utilizado (S/N)';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.IP_SOLICITANTE IS 'IP que solicitó el token';

CREATE INDEX JAVIER.IDX_RESET_TOKEN ON JAVIER.PASSWORD_RESET_TOKENS(TOKEN);
CREATE INDEX JAVIER.IDX_RESET_CLIENTE ON JAVIER.PASSWORD_RESET_TOKENS(CODIGO_CLIENTE);
CREATE INDEX JAVIER.IDX_RESET_USADO ON JAVIER.PASSWORD_RESET_TOKENS(USADO);
