-- CREAR TABLA PARA CONTRASEÑAS EN JAVIER
CREATE TABLE JAVIER.CUSTOMER_PASSWORDS (
  CODIGO_CLIENTE CHAR(13) NOT NULL PRIMARY KEY,
  PASSWORD_HASH VARCHAR(255) NOT NULL,
  INTENTOS_FALLIDOS INTEGER DEFAULT 0,
  BLOQUEADO_HASTA TIMESTAMP,
  ULTIMO_LOGIN TIMESTAMP,
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREAR TABLA PARA REFRESH TOKENS EN JAVIER
CREATE TABLE JAVIER.REFRESH_TOKENS (
  ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CODIGO_CLIENTE CHAR(13) NOT NULL,
  REFRESH_TOKEN VARCHAR(500) NOT NULL,
  DEVICE_INFO VARCHAR(255),
  IP_ADDRESS VARCHAR(50),
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FECHA_EXPIRACION TIMESTAMP NOT NULL,
  REVOCADO CHAR(1) DEFAULT '0'
);

CREATE INDEX REFRESH_TOKENS_IDX1 ON JAVIER.REFRESH_TOKENS(CODIGO_CLIENTE);
CREATE INDEX REFRESH_TOKENS_IDX2 ON JAVIER.REFRESH_TOKENS(REVOCADO);

-- MIGRAR DATOS DE DSEDAC.CLI_AUTH A JAVIER.CUSTOMER_PASSWORDS (si existen)
INSERT INTO JAVIER.CUSTOMER_PASSWORDS (CODIGO_CLIENTE, PASSWORD_HASH, INTENTOS_FALLIDOS, BLOQUEADO_HASTA, ULTIMO_LOGIN, FECHA_CREACION, FECHA_ACTUALIZACION)
SELECT 
  CODIGOCLIENTE,
  PASSWORD_HASH,
  LOGIN_ATTEMPTS,
  LOCKED_UNTIL,
  LAST_LOGIN,
  CREATED_AT,
  UPDATED_AT
FROM DSEDAC.CLI_AUTH;

-- DESPUÉS DE MIGRAR, BORRAR TABLAS DE DSEDAC (solo si migramos correctamente)
-- DROP TABLE DSEDAC.CLI_AUTH;
-- DROP TABLE DSEDAC.CLI_TOKENS;
