
const db = require('./app/config/odbcConfig');

async function rebuildUltimate() {
    try {
        await db.initialize();

        try { await db.query("DROP VIEW JAVIER.V_MEDIOS_POWERBI"); } catch (e) {}
        try { await db.query("DROP VIEW JAVIER.V_MEDIOS_POWERBI_OPTIMIZED"); } catch (e) {}
        try { await db.query("DROP FUNCTION JAVIER.FN_GET_MEDIOS_FULL"); } catch (e) {}

        console.log("Creating ULTIMATE UDTF...");
        const createFunc = `
            CREATE FUNCTION JAVIER.FN_GET_MEDIOS_FULL() 
            RETURNS TABLE (
NUMEROSERIE VARCHAR(20),
TIPOMEDIO VARCHAR(20),
MARCA VARCHAR(40),
CAPACIDAD VARCHAR(10),
DISTRIBUIDOR VARCHAR(40),
NUMEROINVENTARIO VARCHAR(10),
NUMEROCONTRATO VARCHAR(20),
CODIGOCLIENTE VARCHAR(10),
CODIGOVENDEDOR VARCHAR(20),
DIAALTA VARCHAR(50),
MESALTA VARCHAR(50),
ANOALTA VARCHAR(50),
M1ALFC VARCHAR(50),
M1FCAL VARCHAR(50),
OBSERVACIONES1 VARCHAR(40),
OBSERVACIONES2 VARCHAR(40),
OBSERVACIONES3 VARCHAR(40),
OBSERVACIONES4 VARCHAR(40),
OBSERVACIONES5 VARCHAR(40),
OBSERVACIONES6 VARCHAR(40),
ANOFABRICACION VARCHAR(50),
FILTRO01 VARCHAR(10),
FILTRO02 VARCHAR(10),
FILTRO03 VARCHAR(10),
FILTRO04 VARCHAR(10),
FILTRO05 VARCHAR(10),
CODIGOGRUPOMEDIO VARCHAR(10),
CODIGOMODELOMEDIO VARCHAR(20),
CODIGONFC VARCHAR(20),
ESTADOMEDIO VARCHAR(20),
DIABAJA VARCHAR(50),
MESBAJA VARCHAR(50),
ANOBAJA VARCHAR(50),
DIAINSTALACION VARCHAR(50),
MESINSTALACION VARCHAR(50),
ANOINSTALACION VARCHAR(50),
DIAREVISION VARCHAR(50),
MESREVISION VARCHAR(50),
ANOREVISION VARCHAR(50),
MOTIVOVENTA VARCHAR(100),
SUBEMPRESAFACTURAVENTA VARCHAR(20),
EJERCICIOFACTURAVENTA VARCHAR(50),
SERIEFACTURAVENTA VARCHAR(20),
TERMINALFACTURAVENTA VARCHAR(50),
NUMEROFACTURAVENTA VARCHAR(50),
CODIGOARTICULO VARCHAR(10),
CODIGOMEDIO VARCHAR(10),
DESCRIPCIONMEDIO VARCHAR(100),
CODIGOPROVEEDOR VARCHAR(10)
            )
            LANGUAGE SQL 
           READS SQL DATA
           NO EXTERNAL ACTION
           DETERMINISTIC
           RETURN 
               SELECT 
CAST(NUMEROSERIE AS VARCHAR(20)),
CAST(TIPOMEDIO AS VARCHAR(20)),
CAST(MARCA AS VARCHAR(40)),
CAST(CAPACIDAD AS VARCHAR(10)),
CAST(DISTRIBUIDOR AS VARCHAR(40)),
CAST(NUMEROINVENTARIO AS VARCHAR(10)),
CAST(NUMEROCONTRATO AS VARCHAR(20)),
CAST(CODIGOCLIENTE AS VARCHAR(10)),
CAST(CODIGOVENDEDOR AS VARCHAR(20)),
CAST(DIAALTA AS VARCHAR(50)),
CAST(MESALTA AS VARCHAR(50)),
CAST(ANOALTA AS VARCHAR(50)),
CAST(M1ALFC AS VARCHAR(50)),
CAST(M1FCAL AS VARCHAR(50)),
CAST(OBSERVACIONES1 AS VARCHAR(40)),
CAST(OBSERVACIONES2 AS VARCHAR(40)),
CAST(OBSERVACIONES3 AS VARCHAR(40)),
CAST(OBSERVACIONES4 AS VARCHAR(40)),
CAST(OBSERVACIONES5 AS VARCHAR(40)),
CAST(OBSERVACIONES6 AS VARCHAR(40)),
CAST(ANOFABRICACION AS VARCHAR(50)),
CAST(FILTRO01 AS VARCHAR(10)),
CAST(FILTRO02 AS VARCHAR(10)),
CAST(FILTRO03 AS VARCHAR(10)),
CAST(FILTRO04 AS VARCHAR(10)),
CAST(FILTRO05 AS VARCHAR(10)),
CAST(CODIGOGRUPOMEDIO AS VARCHAR(10)),
CAST(CODIGOMODELOMEDIO AS VARCHAR(20)),
CAST(CODIGONFC AS VARCHAR(20)),
CAST(ESTADOMEDIO AS VARCHAR(20)),
CAST(DIABAJA AS VARCHAR(50)),
CAST(MESBAJA AS VARCHAR(50)),
CAST(ANOBAJA AS VARCHAR(50)),
CAST(DIAINSTALACION AS VARCHAR(50)),
CAST(MESINSTALACION AS VARCHAR(50)),
CAST(ANOINSTALACION AS VARCHAR(50)),
CAST(DIAREVISION AS VARCHAR(50)),
CAST(MESREVISION AS VARCHAR(50)),
CAST(ANOREVISION AS VARCHAR(50)),
CAST(MOTIVOVENTA AS VARCHAR(100)),
CAST(SUBEMPRESAFACTURAVENTA AS VARCHAR(20)),
CAST(EJERCICIOFACTURAVENTA AS VARCHAR(50)),
CAST(SERIEFACTURAVENTA AS VARCHAR(20)),
CAST(TERMINALFACTURAVENTA AS VARCHAR(50)),
CAST(NUMEROFACTURAVENTA AS VARCHAR(50)),
CAST(CODIGOARTICULO AS VARCHAR(10)),
CAST(CODIGOMEDIO AS VARCHAR(10)),
CAST(DESCRIPCIONMEDIO AS VARCHAR(100)),
CAST(CODIGOPROVEEDOR AS VARCHAR(10))
               FROM DSEDAC.MEDL1
        `;
        await db.query(createFunc);

        console.log("Creating ULTIMATE VIEW...");
        const createView = `
            CREATE VIEW JAVIER.V_MEDIOS_POWERBI AS 
            SELECT 
                M.*,
                TRIM(C.NOMBRECLIENTE) AS NOMBRE_CLIENTE,
                TRIM(C.NOMBREALTERNATIVO) AS NOMBRE_CLIENTE_ALT,
                TRIM(C.POBLACION) AS POBLACION,
                TRIM(C.PROVINCIA) AS PROVINCIA,
                TRIM(C.DIRECCION) AS DOMICILIO,
                TRIM(C.CODIGORUTA) AS CODIGO_RUTA_CLIENTE,

                -- Categorization
                CASE 
                    WHEN M.DESCRIPCIONMEDIO LIKE '%FRAPE%' OR M.DESCRIPCIONMEDIO LIKE '%FRAPPE%' THEN 'FRAPE'
                    WHEN M.DESCRIPCIONMEDIO LIKE '%NESTLE%' OR M.DESCRIPCIONMEDIO LIKE '%NESTLÉ%' THEN 'NESTLE'
                    WHEN M.DESCRIPCIONMEDIO LIKE '%VITRINA%' THEN 'VITRINA'
                    WHEN M.DESCRIPCIONMEDIO LIKE '%CAFETERA%' THEN 'CAFETERA'
                    ELSE 'OTRO' 
                END AS CATEGORIA,
                
                -- Date Formatter (Trying robust logic or NULL)
                -- M.ANOALTA is now VARCHAR, so we CAST back to INT safely or use string manipulation
                CASE 
                   WHEN TRANSLATE(M.ANOALTA, '0', '0123456789') = '' AND INT(M.ANOALTA) > 1900 THEN
                        DATE( TRIM(M.ANOALTA) || '-' || RIGHT('0'||TRIM(M.MESALTA), 2) || '-' || RIGHT('0'||TRIM(M.DIAALTA), 2) )
                   ELSE NULL
                END AS FECHA_ALTA

            FROM TABLE(JAVIER.FN_GET_MEDIOS_FULL()) AS M
            LEFT JOIN DSEDAC.CLI C ON 
                -- Join Logic: M.CODIGOCLIENTE is VARCHAR(50), C.CODIGOCLIENTE is CHAR(10) or NUMERIC
                -- We trim both to rely on string match which is safest here
                TRIM(M.CODIGOCLIENTE) = TRIM(CAST(C.CODIGOCLIENTE AS VARCHAR(50)))
        `;
        
        await db.query(createView);
        console.log("✅ ULTIMATE VIEW CREATED!");

    } catch(e) { console.error(e); } finally { await db.close(); }
}
rebuildUltimate();
