-- =====================================================
-- SCRIPT DE CREACIÓN DE TABLAS DE SEGURIDAD
-- Esquema: JAVIER
-- Fecha: 2025-11-19
-- =====================================================

-- 1. TABLA: CUSTOMER_CREDENTIALS (Credenciales de clientes)
-- =====================================================
CREATE TABLE JAVIER.CUSTOMER_CREDENTIALS (
    CODIGO_CLIENTE CHAR(13) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    SALT VARCHAR(255) NOT NULL,
    PASSWORD_TYPE VARCHAR(20) NOT NULL DEFAULT 'BCRYPT',
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DEBE_CAMBIAR_PASSWORD CHAR(1) DEFAULT 'N',
    ACTIVO CHAR(1) DEFAULT 'S',
    PRIMARY KEY (CODIGO_CLIENTE)
);

LABEL ON TABLE JAVIER.CUSTOMER_CREDENTIALS IS 'Credenciales seguras de clientes';
LABEL ON COLUMN JAVIER.CUSTOMER_CREDENTIALS.CODIGO_CLIENTE IS 'Código único del cliente';
LABEL ON COLUMN JAVIER.CUSTOMER_CREDENTIALS.PASSWORD_HASH IS 'Hash bcrypt de la contraseña';
LABEL ON COLUMN JAVIER.CUSTOMER_CREDENTIALS.SALT IS 'Salt utilizado para el hash';
LABEL ON COLUMN JAVIER.CUSTOMER_CREDENTIALS.PASSWORD_TYPE IS 'Tipo de password (BCRYPT/NIF/CUSTOM)';
LABEL ON COLUMN JAVIER.CUSTOMER_CREDENTIALS.FECHA_CREACION IS 'Fecha de creación del registro';
LABEL ON COLUMN JAVIER.CUSTOMER_CREDENTIALS.FECHA_MODIFICACION IS 'Última modificación';
LABEL ON COLUMN JAVIER.CUSTOMER_CREDENTIALS.DEBE_CAMBIAR_PASSWORD IS 'Requiere cambio en próximo login (S/N)';
LABEL ON COLUMN JAVIER.CUSTOMER_CREDENTIALS.ACTIVO IS 'Cuenta activa (S/N)';

-- Índice para búsquedas rápidas
CREATE INDEX JAVIER.IDX_CUST_CRED_ACT ON JAVIER.CUSTOMER_CREDENTIALS(ACTIVO);


-- 2. TABLA: LOGIN_ATTEMPTS (Intentos de login)
-- =====================================================
CREATE TABLE JAVIER.LOGIN_ATTEMPTS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CODIGO_CLIENTE CHAR(13) NOT NULL,
    IP_ADDRESS VARCHAR(50),
    USER_AGENT VARCHAR(500),
    INTENTO_EXITOSO CHAR(1) DEFAULT 'N',
    RAZON_FALLO VARCHAR(200),
    FECHA_INTENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

LABEL ON TABLE JAVIER.LOGIN_ATTEMPTS IS 'Registro de intentos de inicio de sesión';
LABEL ON COLUMN JAVIER.LOGIN_ATTEMPTS.ID IS 'ID único autoincremental';
LABEL ON COLUMN JAVIER.LOGIN_ATTEMPTS.CODIGO_CLIENTE IS 'Cliente que intentó login';
LABEL ON COLUMN JAVIER.LOGIN_ATTEMPTS.IP_ADDRESS IS 'Dirección IP del intento';
LABEL ON COLUMN JAVIER.LOGIN_ATTEMPTS.USER_AGENT IS 'Navegador/dispositivo utilizado';
LABEL ON COLUMN JAVIER.LOGIN_ATTEMPTS.INTENTO_EXITOSO IS 'Login exitoso (S/N)';
LABEL ON COLUMN JAVIER.LOGIN_ATTEMPTS.RAZON_FALLO IS 'Motivo del fallo si aplica';
LABEL ON COLUMN JAVIER.LOGIN_ATTEMPTS.FECHA_INTENTO IS 'Timestamp del intento';

-- Índices para consultas de seguridad
CREATE INDEX JAVIER.IDX_LOGIN_ATT_CLIENTE ON JAVIER.LOGIN_ATTEMPTS(CODIGO_CLIENTE);
CREATE INDEX JAVIER.IDX_LOGIN_ATT_FECHA ON JAVIER.LOGIN_ATTEMPTS(FECHA_INTENTO);
CREATE INDEX JAVIER.IDX_LOGIN_ATT_IP ON JAVIER.LOGIN_ATTEMPTS(IP_ADDRESS);


-- 3. TABLA: PASSWORD_RESET_TOKENS (Tokens de recuperación)
-- =====================================================
CREATE TABLE JAVIER.PASSWORD_RESET_TOKENS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CODIGO_CLIENTE CHAR(13) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_EXPIRACION TIMESTAMP NOT NULL,
    USADO CHAR(1) DEFAULT 'N',
    IP_SOLICITANTE VARCHAR(50),
    PRIMARY KEY (ID),
    UNIQUE (TOKEN)
);

LABEL ON TABLE JAVIER.PASSWORD_RESET_TOKENS IS 'Tokens para recuperación de contraseña';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.ID IS 'ID único autoincremental';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.CODIGO_CLIENTE IS 'Cliente solicitante';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.TOKEN IS 'Token único de recuperación';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.EMAIL IS 'Email donde se envió el token';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.FECHA_CREACION IS 'Timestamp de creación';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.FECHA_EXPIRACION IS 'Timestamp de expiración';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.USADO IS 'Token ya utilizado (S/N)';
LABEL ON COLUMN JAVIER.PASSWORD_RESET_TOKENS.IP_SOLICITANTE IS 'IP que solicitó el token';

-- Índices
CREATE INDEX JAVIER.IDX_RESET_TOKEN ON JAVIER.PASSWORD_RESET_TOKENS(TOKEN);
CREATE INDEX JAVIER.IDX_RESET_CLIENTE ON JAVIER.PASSWORD_RESET_TOKENS(CODIGO_CLIENTE);
CREATE INDEX JAVIER.IDX_RESET_USADO ON JAVIER.PASSWORD_RESET_TOKENS(USADO);


-- 4. TABLA: SECURITY_AUDIT (Auditoría de seguridad)
-- =====================================================
CREATE TABLE JAVIER.SECURITY_AUDIT (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    CODIGO_CLIENTE CHAR(13),
    TIPO_EVENTO VARCHAR(50) NOT NULL,
    DESCRIPCION VARCHAR(500),
    IP_ADDRESS VARCHAR(50),
    USER_AGENT VARCHAR(500),
    EXITOSO CHAR(1) DEFAULT 'S',
    FECHA_EVENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

LABEL ON TABLE JAVIER.SECURITY_AUDIT IS 'Auditoría de eventos de seguridad';
LABEL ON COLUMN JAVIER.SECURITY_AUDIT.ID IS 'ID único autoincremental';
LABEL ON COLUMN JAVIER.SECURITY_AUDIT.CODIGO_CLIENTE IS 'Cliente involucrado (si aplica)';
LABEL ON COLUMN JAVIER.SECURITY_AUDIT.TIPO_EVENTO IS 'Tipo de evento (LOGIN, LOGOUT, PASSWORD_CHANGE, etc)';
LABEL ON COLUMN JAVIER.SECURITY_AUDIT.DESCRIPCION IS 'Descripción detallada del evento';
LABEL ON COLUMN JAVIER.SECURITY_AUDIT.IP_ADDRESS IS 'Dirección IP';
LABEL ON COLUMN JAVIER.SECURITY_AUDIT.USER_AGENT IS 'Navegador/dispositivo';
LABEL ON COLUMN JAVIER.SECURITY_AUDIT.EXITOSO IS 'Operación exitosa (S/N)';
LABEL ON COLUMN JAVIER.SECURITY_AUDIT.FECHA_EVENTO IS 'Timestamp del evento';

-- Índices para análisis de seguridad
CREATE INDEX JAVIER.IDX_AUDIT_CLIENTE ON JAVIER.SECURITY_AUDIT(CODIGO_CLIENTE);
CREATE INDEX JAVIER.IDX_AUDIT_FECHA ON JAVIER.SECURITY_AUDIT(FECHA_EVENTO);
CREATE INDEX JAVIER.IDX_AUDIT_TIPO ON JAVIER.SECURITY_AUDIT(TIPO_EVENTO);
CREATE INDEX JAVIER.IDX_AUDIT_IP ON JAVIER.SECURITY_AUDIT(IP_ADDRESS);


-- 5. TABLA: CUSTOMER_EMAILS (Emails de clientes)
-- =====================================================
CREATE TABLE JAVIER.CUSTOMER_EMAILS (
    CODIGO_CLIENTE CHAR(13) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    VERIFICADO CHAR(1) DEFAULT 'N',
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_VERIFICACION TIMESTAMP,
    PRIMARY KEY (CODIGO_CLIENTE),
    UNIQUE (EMAIL)
);

LABEL ON TABLE JAVIER.CUSTOMER_EMAILS IS 'Emails de clientes para recuperación';
LABEL ON COLUMN JAVIER.CUSTOMER_EMAILS.CODIGO_CLIENTE IS 'Código único del cliente';
LABEL ON COLUMN JAVIER.CUSTOMER_EMAILS.EMAIL IS 'Dirección de email';
LABEL ON COLUMN JAVIER.CUSTOMER_EMAILS.VERIFICADO IS 'Email verificado (S/N)';
LABEL ON COLUMN JAVIER.CUSTOMER_EMAILS.FECHA_CREACION IS 'Fecha de registro del email';
LABEL ON COLUMN JAVIER.CUSTOMER_EMAILS.FECHA_VERIFICACION IS 'Fecha de verificación';

-- Índice para búsqueda por email
CREATE INDEX JAVIER.IDX_CUST_EMAIL ON JAVIER.CUSTOMER_EMAILS(EMAIL);


-- =====================================================
-- VERIFICACIÓN FINAL
-- =====================================================
-- Puedes ejecutar esto para verificar que las tablas se crearon:
SELECT TABLE_NAME, TABLE_TEXT 
FROM QSYS2.SYSTABLES 
WHERE TABLE_SCHEMA = 'JAVIER' 
  AND TABLE_NAME IN (
    'CUSTOMER_CREDENTIALS',
    'LOGIN_ATTEMPTS', 
    'PASSWORD_RESET_TOKENS',
    'SECURITY_AUDIT',
    'CUSTOMER_EMAILS'
  )
ORDER BY TABLE_NAME;

-- =====================================================
-- NOTAS IMPORTANTES
-- =====================================================
-- 1. Estas tablas están en el esquema JAVIER, no en DSEDAC
-- 2. Después de crear las tablas, debes actualizar el archivo .env:
--    SECURITY_SCHEMA=JAVIER
-- 3. O modificar authService.js para buscar en JAVIER en vez de DSEDAC
-- =====================================================
