/**
 * TEST RÁPIDO - Verificar filtros específicos
 * Ejecutar: node scripts/test-rapido.js
 */
const db = require('../app/config/odbcConfig');

(async () => {
  await db.initialize();
  console.log('TEST RÁPIDO\n');

  const F = "'700', '701', '702', '703', '704', '705', '706'";
  const C = "'AB', 'RG', 'VT'";

  // Test básico como antes
  const r = await db.query(`
    SELECT TRIM(LAC.TIPOVENTA) AS TV, SUM(COALESCE(LAC.CANTIDADENVASES,0)) AS CAJAS
    FROM DSEDAC.CAC CAC
    INNER JOIN DSEDAC.LAC LAC ON 
      LAC.SUBEMPRESAALBARAN = CAC.SUBEMPRESAALBARAN AND
      LAC.EJERCICIOALBARAN = CAC.EJERCICIOALBARAN AND
      LAC.SERIEALBARAN = CAC.SERIEALBARAN AND
      LAC.TERMINALALBARAN = CAC.TERMINALALBARAN AND
      LAC.NUMEROALBARAN = CAC.NUMEROALBARAN
    INNER JOIN DSEDAC.ART ART ON TRIM(LAC.CODIGOARTICULO) = TRIM(ART.CODIGOARTICULO)
    WHERE CAC.ANODOCUMENTO = 2026 AND CAC.MESDOCUMENTO = 4
      AND TRIM(CAC.CODIGOCLIENTEFACTURA) LIKE '43%'
      AND CAC.NUMEROFACTURA > 0
      AND TRIM(ART.CODIGOFAMILIA) IN (${F})
      AND TRIM(LAC.CLASELINEA) IN (${C})
    GROUP BY TRIM(LAC.TIPOVENTA)
  `);

  let cc = 0, sc = 0;
  r.forEach(x => {
    if (x.TV === 'CC') cc = Number(x.CAJAS);
    if (x.TV === 'SC') sc = Number(x.CAJAS);
  });

  console.log('RESULTADO: CC=' + cc + ', SC=' + sc);
  console.log('ESPERADO: CC=3865, SC=11');

  // Diferentes filtros
  console.log('\n--- VARIANTES ---');

  // Sin NUMEROFACTURA > 0
  const r2 = await db.query(`
    SELECT TRIM(LAC.TIPOVENTA) AS TV, SUM(COALESCE(LAC.CANTIDADENVASES,0)) AS CAJAS
    FROM DSEDAC.CAC CAC
    INNER JOIN DSEDAC.LAC LAC ON LAC.NUMEROALBARAN = CAC.NUMEROALBARAN
    INNER JOIN DSEDAC.ART ART ON TRIM(LAC.CODIGOARTICULO) = TRIM(ART.CODIGOARTICULO)
    WHERE CAC.ANODOCUMENTO = 2026 AND CAC.MESDOCUMENTO = 4
      AND TRIM(CAC.CODIGOCLIENTEFACTURA) LIKE '43%'
      AND TRIM(ART.CODIGOFAMILIA) IN (${F})
      AND TRIM(LAC.CLASELINEA) IN (${C})
    GROUP BY TRIM(LAC.TIPOVENTA)
  `);
  let cc2 = 0, sc2 = 0;
  r2.forEach(x => { if (x.TV === 'CC') cc2 = Number(x.CAJAS); if (x.TV === 'SC') sc2 = Number(x.CAJAS); });
  console.log('Sin NUMEROFACTURA>0: CC=' + cc2 + ', SC=' + sc2);

  // Con ANOFACTURA
  const r3 = await db.query(`
    SELECT TRIM(LAC.TIPOVENTA) AS TV, SUM(COALESCE(LAC.CANTIDADENVASES,0)) AS CAJAS
    FROM DSEDAC.CAC CAC
    INNER JOIN DSEDAC.LAC LAC ON LAC.NUMEROALBARAN = CAC.NUMEROALBARAN
    INNER JOIN DSEDAC.ART ART ON TRIM(LAC.CODIGOARTICULO) = TRIM(ART.CODIGOARTICULO)
    WHERE CAC.ANOFACTURA = 2026 AND CAC.MESFACTURA = 4
      AND TRIM(CAC.CODIGOCLIENTEFACTURA) LIKE '43%'
      AND CAC.NUMEROFACTURA > 0
      AND TRIM(ART.CODIGOFAMILIA) IN (${F})
      AND TRIM(LAC.CLASELINEA) IN (${C})
    GROUP BY TRIM(LAC.TIPOVENTA)
  `);
  let cc3 = 0, sc3 = 0;
  r3.forEach(x => { if (x.TV === 'CC') cc3 = Number(x.CAJAS); if (x.TV === 'SC') sc3 = Number(x.CAJAS); });
  console.log('ANOFACTURA/MESFACTURA: CC=' + cc3 + ', SC=' + sc3);

  // Con EJERCICIOFACTURA
  const r4 = await db.query(`
    SELECT TRIM(LAC.TIPOVENTA) AS TV, SUM(COALESCE(LAC.CANTIDADENVASES,0)) AS CAJAS
    FROM DSEDAC.CAC CAC
    INNER JOIN DSEDAC.LAC LAC ON LAC.NUMEROALBARAN = CAC.NUMEROALBARAN
    INNER JOIN DSEDAC.ART ART ON TRIM(LAC.CODIGOARTICULO) = TRIM(ART.CODIGOARTICULO)
    WHERE CAC.EJERCICIOFACTURA = 2026 AND CAC.MESFACTURA = 4
      AND TRIM(CAC.CODIGOCLIENTEFACTURA) LIKE '43%'
      AND CAC.NUMEROFACTURA > 0
      AND TRIM(ART.CODIGOFAMILIA) IN (${F})
      AND TRIM(LAC.CLASELINEA) IN (${C})
    GROUP BY TRIM(LAC.TIPOVENTA)
  `);
  let cc4 = 0, sc4 = 0;
  r4.forEach(x => { if (x.TV === 'CC') cc4 = Number(x.CAJAS); if (x.TV === 'SC') sc4 = Number(x.CAJAS); });
  console.log('EJERCICIOFACTURA/MESFACTURA: CC=' + cc4 + ', SC=' + sc4);

  // Con ANODOCUMENTO pero sin NUMEROFACTURA (debería ser igual)
  const r5 = await db.query(`
    SELECT TRIM(LAC.TIPOVENTA) AS TV, SUM(COALESCE(LAC.CANTIDADENVASES,0)) AS CAJAS
    FROM DSEDAC.CAC CAC
    INNER JOIN DSEDAC.LAC LAC ON LAC.NUMEROALBARAN = CAC.NUMEROALBARAN
    INNER JOIN DSEDAC.ART ART ON TRIM(LAC.CODIGOARTICULO) = TRIM(ART.CODIGOARTICULO)
    WHERE CAC.ANODOCUMENTO = 2026 AND CAC.MESDOCUMENTO = 4
      AND TRIM(CAC.CODIGOCLIENTEFACTURA) LIKE '43%'
      AND TRIM(ART.CODIGOFAMILIA) IN (${F})
      AND TRIM(LAC.CLASELINEA) IN (${C})
    GROUP BY TRIM(LAC.TIPOVENTA)
  `);
  let cc5 = 0, sc5 = 0;
  r5.forEach(x => { if (x.TV === 'CC') cc5 = Number(x.CAJAS); if (x.TV === 'SC') sc5 = Number(x.CAJAS); });
  console.log('ANODOCUMENTO (sin NUMEROFACTURA): CC=' + cc5 + ', SC=' + sc5);

  process.exit(0);
})();