/**
 * Test sin NUMEROFACTURA filter
 */
const db = require('../app/config/odbcConfig');

(async () => {
  await db.initialize();
  console.log('TEST SIN NUMEROFACTURA>0\n');

  const F = "'700', '701', '702', '703', '704', '705', '706'";
  const C = "'AB', 'RG', 'VT'";

  // Mi actual: NUMEROFACTURA > 0
  const r1 = await db.query(`
    SELECT TRIM(LAC.TIPOVENTA) AS TV, SUM(COALESCE(LAC.CANTIDADENVASES,0)) AS CAJAS
    FROM DSEDAC.CAC CAC
    INNER JOIN DSEDAC.LAC LAC ON 
      LAC.SUBEMPRESAALBARAN = CAC.SUBEMPRESAALBARAN AND
      LAC.EJERCICIOALBARAN = CAC.EJERCICIOALBARAN AND
      LAC.SERIEALBARAN = CAC.SERIEALBARAN AND
      LAC.TERMINALALBARAN = CAC.TERMINALALBARAN AND
      LAC.NUMEROALBARAN = CAC.NUMEROALBARAN
    INNER JOIN DSEDAC.ART ART ON TRIM(LAC.CODIGOARTICULO) = TRIM(ART.CODIGOARTICULO)
    WHERE CAC.ANODOCUMENTO = 2026 AND CAC.MESDOCUMENTO = 4
      AND TRIM(CAC.CODIGOCLIENTEFACTURA) LIKE '43%'
      AND CAC.NUMEROFACTURA > 0
      AND TRIM(ART.CODIGOFAMILIA) IN (${F})
      AND TRIM(LAC.CLASELINEA) IN (${C})
    GROUP BY TRIM(LAC.TIPOVENTA)
  `);
  let cc1=0, sc1=0; r1.forEach(x=>{if(x.TV==='CC')cc1=x.CAJAS;if(x.TV==='SC')sc1=x.CAJAS;});
  console.log('Con NUM>0: CC=' + cc1 + ', SC=' + sc1);

  // Sin filtro NUMEROFACTURA
  const r2 = await db.query(`
    SELECT TRIM(LAC.TIPOVENTA) AS TV, SUM(COALESCE(LAC.CANTIDADENVASES,0)) AS CAJAS
    FROM DSEDAC.CAC CAC
    INNER JOIN DSEDAC.LAC LAC ON 
      LAC.SUBEMPRESAALBARAN = CAC.SUBEMPRESAALBARAN AND
      LAC.EJERCICIOALBARAN = CAC.EJERCICIOALBARAN AND
      LAC.SERIEALBARAN = CAC.SERIEALBARAN AND
      LAC.TERMINALALBARAN = CAC.TERMINALALBARAN AND
      LAC.NUMEROALBARAN = CAC.NUMEROALBARAN
    INNER JOIN DSEDAC.ART ART ON TRIM(LAC.CODIGOARTICULO) = TRIM(ART.CODIGOARTICULO)
    WHERE CAC.ANODOCUMENTO = 2026 AND CAC.MESDOCUMENTO = 4
      AND TRIM(CAC.CODIGOCLIENTEFACTURA) LIKE '43%'
      AND TRIM(ART.CODIGOFAMILIA) IN (${F})
      AND TRIM(LAC.CLASELINEA) IN (${C})
    GROUP BY TRIM(LAC.TIPOVENTA)
  `);
  let cc2=0, sc2=0; r2.forEach(x=>{if(x.TV==='CC')cc2=x.CAJAS;if(x.TV==='SC')sc2=x.CAJAS;});
  console.log('Sin NUM>0: CC=' + cc2 + ', SC=' + sc2);

  // Cuántos hay sin NUMEROFACTURA?
  const sinNum = await db.query(`
    SELECT COUNT(*) AS N FROM DSEDAC.CAC CAC
    WHERE CAC.ANODOCUMENTO = 2026 AND CAC.MESDOCUMENTO = 4
      AND TRIM(CAC.CODIGOCLIENTEFACTURA) LIKE '43%'
      AND CAC.NUMEROFACTURA IS NULL OR CAC.NUMEROFACTURA = 0
  `);
  console.log('\nRegistros sin NUMEROFACTURA: ' + sinNum[0].N);

  // Diferencia
  console.log('\nDiferencia sin NUM>0: CC=' + (cc2-cc1) + ', SC=' + (sc2-sc1));

  // Ahora probar ABS sin NUM>0
  const r3 = await db.query(`
    SELECT TRIM(LAC.TIPOVENTA) AS TV, SUM(ABS(COALESCE(LAC.CANTIDADENVASES,0))) AS CAJAS
    FROM DSEDAC.CAC CAC
    INNER JOIN DSEDAC.LAC LAC ON 
      LAC.SUBEMPRESAALBARAN = CAC.SUBEMPRESAALBARAN AND
      LAC.EJERCICIOALBARAN = CAC.EJERCICIOALBARAN AND
      LAC.SERIEALBARAN = CAC.SERIEALBARAN AND
      LAC.TERMINALALBARAN = CAC.TERMINALALBARAN AND
      LAC.NUMEROALBARAN = CAC.NUMEROALBARAN
    INNER JOIN DSEDAC.ART ART ON TRIM(LAC.CODIGOARTICULO) = TRIM(ART.CODIGOARTICULO)
    WHERE CAC.ANODOCUMENTO = 2026 AND CAC.MESDOCUMENTO = 4
      AND TRIM(CAC.CODIGOCLIENTEFACTURA) LIKE '43%'
      AND TRIM(ART.CODIGOFAMILIA) IN (${F})
      AND TRIM(LAC.CLASELINEA) IN (${C})
    GROUP BY TRIM(LAC.TIPOVENTA)
  `);
  let cc3=0, sc3=0; r3.forEach(x=>{if(x.TV==='CC')cc3=x.CAJAS;if(x.TV==='SC')sc3=x.CAJAS;});
  console.log('ABS sin NUM>0: CC=' + cc3 + ', SC=' + sc3);

  console.log('\n=== RESUMEN ===');
  console.log('Mi actual: CC=' + cc1 + ', SC=' + sc1);
  console.log('ABS sin NUM>0: CC=' + cc3 + ', SC=' + sc3);
  console.log('Objetivo: CC=3865, SC=11');
  console.log('Diferencia: CC=' + (3865-cc3) + ', SC=' + (11-sc3));

  process.exit(0);
})();