/*
 * CONSULTA MAESTRA PARA POWER BI - INFORME MEDIOS
 * ===============================================
 * 
 * NOTA TÉCNICA: No se puede crear una VISTA en AS400 sobre el archivo MEDL1 (Error SQL7010).
 * SOLUCIÓN: Usar esta Consulta SQL Directa que funciona EXACTAMENTE igual.
 * 
 * INSTRUCCIONES:
 * 1. Copiar este código.
 * 2. En Power BI: Obtener Datos -> ODBC -> Opciones avanzadas -> Pegar en "Declaración SQL".
 */

SELECT 
    -- == IDENTIFICACIÓN DEL MEDIO ==
    M.CODIGOMEDIO,
    M.NUMEROSERIE,
    M.CODIGONFC,
    M.TIPOMEDIO,
    M.MARCA,
    M.CAPACIDAD,
    M.DISTRIBUIDOR,
    M.NUMEROINVENTARIO,
    M.NUMEROCONTRATO,
    M.CODIGOVENDEDOR,
    M.CODIGOPROVEEDOR,
    M.CODIGOARTICULO,
    
    -- == OBSERVACIONES Y ESTADO ==
    M.DESCRIPCIONMEDIO,
    M.ESTADOMEDIO,
    M.OBSERVACIONES1,
    M.OBSERVACIONES2,
    M.OBSERVACIONES3,
    M.MOTIVOVENTA,
    
    -- == CATEGORIZACIÓN AUTOMÁTICA (Replica Pestañas Excel) ==
    CASE 
        WHEN M.DESCRIPCIONMEDIO LIKE '%FRAPE%' OR M.DESCRIPCIONMEDIO LIKE '%FRAPPE%' THEN 'FRAPE'
        WHEN M.DESCRIPCIONMEDIO LIKE '%NESTLE%' OR M.DESCRIPCIONMEDIO LIKE '%NESTLÉ%' THEN 'NESTLE'
        WHEN M.DESCRIPCIONMEDIO LIKE '%VITRINA%' THEN 'VITRINA'
        WHEN M.DESCRIPCIONMEDIO LIKE '%CAFETERA%' THEN 'CAFETERA'
        ELSE 'GENERAL' 
    END AS CATEGORIA_DETECTADA,

    -- == MODELO ==
    M.CODIGOMODELOMEDIO,
    COALESCE(MOD.DESCRIPCIONMODELOMEDIO, 'DESCONOCIDO') AS MODELO_DESC,

    -- == FECHAS REALES (Convertidas para Power BI) ==
    CASE WHEN M.ANOALTA > 1900 THEN DATE(RTRIM(CHAR(M.ANOALTA)) || '-' || RTRIM(CHAR(M.MESALTA)) || '-' || RTRIM(CHAR(M.DIAALTA))) ELSE NULL END AS FECHA_ALTA,
    CASE WHEN M.ANOBAJA > 1900 THEN DATE(RTRIM(CHAR(M.ANOBAJA)) || '-' || RTRIM(CHAR(M.MESBAJA)) || '-' || RTRIM(CHAR(M.DIABAJA))) ELSE NULL END AS FECHA_BAJA,
    CASE WHEN M.ANOINSTALACION > 1900 THEN DATE(RTRIM(CHAR(M.ANOINSTALACION)) || '-' || RTRIM(CHAR(M.MESINSTALACION)) || '-' || RTRIM(CHAR(M.DIAINSTALACION))) ELSE NULL END AS FECHA_INSTALACION,
    CASE WHEN M.ANOREVISION > 1900 THEN DATE(RTRIM(CHAR(M.ANOREVISION)) || '-' || RTRIM(CHAR(M.MESREVISION)) || '-' || RTRIM(CHAR(M.DIAREVISION))) ELSE NULL END AS FECHA_REVISION,

    -- == DATOS DEL CLIENTE ==
    M.CODIGOCLIENTE,
    C.LCNCL AS NOMBRE_CLIENTE,
    TRIM(C.LCDOPO) || ' ' || TRIM(C.LCPOBL) AS DIRECCION_COMPLETA,
    C.LCPOBL AS POBLACION,
    C.LCPROV AS PROVINCIA,
    C.LCRUTA AS RUTA,
    
    -- Delegación basada en Provincia (Lógica aproximada, ajustar según necesidad real)
    CASE 
        WHEN C.LCPROV LIKE '%ALMER%' OR C.LCPROV LIKE '%ALM%' THEN 'ALMERIA'
        ELSE 'OTRA'
    END AS DELEGACION_CALCULADA,

    -- Estado Simplificado para Gráficos
    CASE 
        WHEN M.ANOBAJA > 1900 THEN 'BAJA'
        WHEN M.ESTADOMEDIO LIKE '%DISPONIBLE%' THEN 'DISPONIBLE'
        ELSE 'ACTIVO' 
    END AS ESTADO_RESUMEN,
    
    -- Contador
    1 AS CANTIDAD

FROM DSEDAC.MEDL1 M

-- JOIN con CLIENTES
LEFT JOIN DSED.LACLAE C ON M.CODIGOCLIENTE = C.LCCL 

-- JOIN con MODELOS
LEFT JOIN DSEDAC.MMDL1 MOD ON M.CODIGOMODELOMEDIO = MOD.CODIGOMODELOMEDIO

WHERE 
    -- Filtro de "Higiene" de datos: Clientes activos o medios relevantes
    C.LCYEAB >= 2025 
    OR M.ESTADOMEDIO LIKE '%DISPONIBLE%'
    OR M.ANOBAJA >= 2024 -- Incluir bajas recientes
