-- DOCUMENTACIÓN TÉCNICA - SOLUCIÓN VIEW OVER LOGICAL FILE
-- Autor: Asistente Senior
-- Objeto: JAVIER.V_MEDIOS_POWERBI
-- Problema: Error SQL7010 al crear vista sobre DSEDAC.MEDL1 (Archivo Lógico)

-- PASO 1: Wrapper Function (UDTF)
-- Encapsula la lectura del archivo lógico. AS400 permite funciones que lean datos.
CREATE OR REPLACE FUNCTION JAVIER.FN_GET_MEDIOS() 
RETURNS TABLE (
    CODIGOMEDIO CHAR(10),
    NUMEROSERIE CHAR(20), 
    DESCRIPCIONMEDIO CHAR(60),
    ESTADOMEDIO CHAR(20),
    CODIGOCLIENTE NUMERIC(5,0),
    ANOALTA NUMERIC(4,0),
    MESALTA NUMERIC(2,0),
    DIAALTA NUMERIC(2,0)
)
LANGUAGE SQL 
READS SQL DATA
NO EXTERNAL ACTION
DETERMINISTIC
RETURN 
    SELECT 
        CODIGOMEDIO, NUMEROSERIE, DESCRIPCIONMEDIO, ESTADOMEDIO, CODIGOCLIENTE,
        ANOALTA, MESALTA, DIAALTA
    FROM DSEDAC.MEDL1;

-- PASO 2: La Vista
-- Selecciona de la función como si fuera una tabla.
CREATE OR REPLACE VIEW JAVIER.V_MEDIOS_POWERBI AS 
SELECT 
    CODIGOMEDIO,
    NUMEROSERIE,
    DESCRIPCIONMEDIO,
    ESTADOMEDIO,
    CODIGOCLIENTE,
    -- Lógica de negocio (Nestlé, Frape...)
    CASE 
        WHEN DESCRIPCIONMEDIO LIKE '%FRAPE%' OR DESCRIPCIONMEDIO LIKE '%FRAPPE%' THEN 'FRAPE'
        WHEN DESCRIPCIONMEDIO LIKE '%NESTLE%' OR DESCRIPCIONMEDIO LIKE '%NESTLÉ%' THEN 'NESTLE'
        WHEN DESCRIPCIONMEDIO LIKE '%VITRINA%' THEN 'VITRINA'
        WHEN DESCRIPCIONMEDIO LIKE '%CAFETERA%' THEN 'CAFETERA'
        ELSE 'OTRO' 
    END AS CATEGORIA,
    -- Conversión de Fechas
    CASE WHEN ANOALTA > 1900 THEN DATE(RTRIM(CHAR(ANOALTA))||'-'||RTRIM(CHAR(MESALTA))||'-'||RTRIM(CHAR(DIAALTA))) ELSE NULL END AS FECHA_ALTA
FROM TABLE(JAVIER.FN_GET_MEDIOS()) AS T;
